# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/gig_ethernet_pcs_pma_0_example_design.xdc

# XDC: new/test_23.xdc

# XDC: EDF_SiTCP_constraints.xdc

# IP: ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0 || ORIG_REF_NAME==gig_ethernet_pcs_pma_0} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
