# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
create_project -in_memory -part xcku060-ffva1517-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/DELL/Desktop/mft_k7_project/8.7/SiTCP_Netlist_for_Kintex_UltraScale-master/SiTCP_XCKU_32K_BBT_V110.V
  C:/Users/DELL/Desktop/mft_k7_project/8.7/SiTCP_Netlist_for_Kintex_UltraScale-master/TIMER.v
  C:/Users/DELL/Desktop/mft_k7_project/8.7/SiTCP_Netlist_for_Kintex_UltraScale-master/WRAP_SiTCP_GMII_XCKU_32K.V
  C:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/new/fifio_gen.v
  C:/Users/DELL/Desktop/mft_k7_project/sitcp_test/project_6_kin_ula_smgii/gig_ethernet_pcs_pma_0_ex/imports/gig_ethernet_pcs_pma_0_clocking.v
  C:/Users/DELL/Desktop/mft_k7_project/sitcp_test/project_6_kin_ula_smgii/gig_ethernet_pcs_pma_0_ex/imports/gig_ethernet_pcs_pma_0_example_design.v
  C:/Users/DELL/Desktop/mft_k7_project/sitcp_test/project_6_kin_ula_smgii/gig_ethernet_pcs_pma_0_ex/imports/gig_ethernet_pcs_pma_0_reset_sync_ex.v
  C:/Users/DELL/Desktop/mft_k7_project/sitcp_test/project_6_kin_ula_smgii/gig_ethernet_pcs_pma_0_ex/imports/gig_ethernet_pcs_pma_0_resets.v
  C:/Users/DELL/Desktop/mft_k7_project/sitcp_test/project_6_kin_ula_smgii/gig_ethernet_pcs_pma_0_ex/imports/gig_ethernet_pcs_pma_0_support.v
  C:/Users/DELL/Desktop/mft_k7_project/sitcp_test/project_6_kin_ula_smgii/gig_ethernet_pcs_pma_0_ex/imports/gig_ethernet_pcs_pma_0_sync_block_ex.v
  C:/Users/DELL/Desktop/mft_k7_project/sitcp_test/project_6_kin_ula_smgii/gig_ethernet_pcs_pma_0_ex/imports/gig_ethernet_pcs_pma_0_tx_elastic_buffer.v
  C:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/new/TOP_file.v
}
read_ip -quiet C:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
set_property used_in_implementation false [get_files -all c:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/ip_0/synth/gig_ethernet_pcs_pma_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/ip_0/synth/gig_ethernet_pcs_pma_0_gt.xdc]

read_ip -quiet C:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all c:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_edif C:/Users/DELL/Desktop/mft_k7_project/8.7/SiTCP_Netlist_for_Kintex_UltraScale-master/SiTCP_XCKU_32K_BBT_V110.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/constrs_3/new/gig_ethernet_pcs_pma_0_example_design.xdc
set_property used_in_implementation false [get_files C:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/constrs_3/new/gig_ethernet_pcs_pma_0_example_design.xdc]

read_xdc C:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/constrs_3/new/test_23.xdc
set_property used_in_implementation false [get_files C:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/constrs_3/new/test_23.xdc]

read_xdc C:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/constrs_3/EDF_SiTCP_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/constrs_3/EDF_SiTCP_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TOP_file -part xcku060-ffva1517-2-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP_file.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_file_utilization_synth.rpt -pb TOP_file_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
