# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/DELL/Desktop/mft_k7_project/8.7/gig_ethernet_pcs_pma_0_ex/imports/gig_ethernet_pcs_pma_0_example_design.xdc

# IP: ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0 || ORIG_REF_NAME==gig_ethernet_pcs_pma_0} -quiet] -quiet
