set_property SRC_FILE_INFO {cfile:C:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/constrs_3/new/gig_ethernet_pcs_pma_0_example_design.xdc rfile:../../../project_1.srcs/constrs_3/new/gig_ethernet_pcs_pma_0_example_design.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/constrs_3/new/test_23.xdc rfile:../../../project_1.srcs/constrs_3/new/test_23.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/DELL/Desktop/mft_k7_project/8.7/project_1/project_1.srcs/constrs_3/EDF_SiTCP_constraints.xdc rfile:../../../project_1.srcs/constrs_3/EDF_SiTCP_constraints.xdc id:3} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 3.333 -name io_refclk  [get_ports io_refclk]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.00 -name independent_clock  [get_ports independent_clock]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 5.00 -name sysclk_200   [get_ports sysclk_200]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 -name gmii_tx_clk  [get_ports gmii_tx_clk]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks gmii_tx_clk] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *tx_elastic_buffer_inst/tx_en_fifo_reg1*}] -filter {REF_PIN_NAME =~ D}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks gmii_tx_clk] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *tx_elastic_buffer_inst/tx_er_fifo_reg1*}] -filter {REF_PIN_NAME =~ D}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks gmii_tx_clk] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~ *tx_elastic_buffer_inst/txd_fifo_reg1*}] -filter {REF_PIN_NAME =~ D}]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L18 [get_ports firefly_reset_3_rx]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports firefly_reset_3_tx]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F38 [get_ports CLK_200_n]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E38 [get_ports CLK_200_p]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV2 [get_ports rxp]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV1 [get_ports rxn]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV6 [get_ports txp]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV5 [get_ports txn]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT9 [get_ports gtrefclk_n]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT10 [get_ports gtrefclk_p]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 3 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list instance_name/inst/clk_out2]]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {pcspma/core_support_i/an_adv_config_vector[0]} {pcspma/core_support_i/an_adv_config_vector[1]} {pcspma/core_support_i/an_adv_config_vector[2]} {pcspma/core_support_i/an_adv_config_vector[3]} {pcspma/core_support_i/an_adv_config_vector[4]} {pcspma/core_support_i/an_adv_config_vector[5]} {pcspma/core_support_i/an_adv_config_vector[6]} {pcspma/core_support_i/an_adv_config_vector[7]} {pcspma/core_support_i/an_adv_config_vector[8]} {pcspma/core_support_i/an_adv_config_vector[9]} {pcspma/core_support_i/an_adv_config_vector[10]} {pcspma/core_support_i/an_adv_config_vector[11]} {pcspma/core_support_i/an_adv_config_vector[12]} {pcspma/core_support_i/an_adv_config_vector[13]} {pcspma/core_support_i/an_adv_config_vector[14]} {pcspma/core_support_i/an_adv_config_vector[15]}]]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {pcspma/core_support_i/status_vector[0]} {pcspma/core_support_i/status_vector[1]} {pcspma/core_support_i/status_vector[2]} {pcspma/core_support_i/status_vector[3]} {pcspma/core_support_i/status_vector[4]} {pcspma/core_support_i/status_vector[5]} {pcspma/core_support_i/status_vector[6]} {pcspma/core_support_i/status_vector[7]} {pcspma/core_support_i/status_vector[8]} {pcspma/core_support_i/status_vector[9]} {pcspma/core_support_i/status_vector[10]} {pcspma/core_support_i/status_vector[11]} {pcspma/core_support_i/status_vector[12]} {pcspma/core_support_i/status_vector[13]} {pcspma/core_support_i/status_vector[14]} {pcspma/core_support_i/status_vector[15]}]]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {pcspma/core_support_i/configuration_vector[0]} {pcspma/core_support_i/configuration_vector[1]} {pcspma/core_support_i/configuration_vector[2]} {pcspma/core_support_i/configuration_vector[3]} {pcspma/core_support_i/configuration_vector[4]}]]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {pcspma/core_support_i/gmii_rxd[0]} {pcspma/core_support_i/gmii_rxd[1]} {pcspma/core_support_i/gmii_rxd[2]} {pcspma/core_support_i/gmii_rxd[3]} {pcspma/core_support_i/gmii_rxd[4]} {pcspma/core_support_i/gmii_rxd[5]} {pcspma/core_support_i/gmii_rxd[6]} {pcspma/core_support_i/gmii_rxd[7]}]]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {pcspma/core_support_i/gmii_txd[0]} {pcspma/core_support_i/gmii_txd[1]} {pcspma/core_support_i/gmii_txd[2]} {pcspma/core_support_i/gmii_txd[3]} {pcspma/core_support_i/gmii_txd[4]} {pcspma/core_support_i/gmii_txd[5]} {pcspma/core_support_i/gmii_txd[6]} {pcspma/core_support_i/gmii_txd[7]}]]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list pcspma/core_support_i/an_interrupt]]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list pcspma/core_support_i/an_restart_config]]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list pcspma/core_support_i/cplllock]]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list pcspma/core_support_i/gmii_isolate]]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list pcspma/core_support_i/gmii_rx_dv]]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list pcspma/core_support_i/gmii_rx_er]]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list pcspma/core_support_i/gmii_tx_en]]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list pcspma/core_support_i/gmii_tx_er]]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list pcspma/core_support_i/gtpowergood]]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list pcspma/core_support_i/independent_clock_bufg]]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list pcspma/core_support_i/mmcm_locked]]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list pcspma/core_support_i/mmcm_reset]]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list pcspma/core_support_i/pma_reset]]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list pcspma/core_support_i/reset]]
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list pcspma/core_support_i/resetdone]]
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list pcspma/core_support_i/signal_detect]]
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk_out2]
set_property src_info {type:XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {{sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank0LastWrAddr_reg[0]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank0LastWrAddr_reg[10]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank0LastWrAddr_reg[1]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank0LastWrAddr_reg[2]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank0LastWrAddr_reg[3]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank0LastWrAddr_reg[4]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank0LastWrAddr_reg[5]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank0LastWrAddr_reg[6]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank0LastWrAddr_reg[7]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank0LastWrAddr_reg[8]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank0LastWrAddr_reg[9]/C}}] -to [get_pins {{sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank0LastWrAddr_reg[0]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank0LastWrAddr_reg[10]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank0LastWrAddr_reg[1]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank0LastWrAddr_reg[2]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank0LastWrAddr_reg[3]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank0LastWrAddr_reg[4]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank0LastWrAddr_reg[5]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank0LastWrAddr_reg[6]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank0LastWrAddr_reg[7]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank0LastWrAddr_reg[8]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank0LastWrAddr_reg[9]/D}}] 5.000
set_property src_info {type:XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {{sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank1LastWrAddr_reg[0]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank1LastWrAddr_reg[10]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank1LastWrAddr_reg[1]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank1LastWrAddr_reg[2]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank1LastWrAddr_reg[3]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank1LastWrAddr_reg[4]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank1LastWrAddr_reg[5]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank1LastWrAddr_reg[6]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank1LastWrAddr_reg[7]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank1LastWrAddr_reg[8]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/dlyBank1LastWrAddr_reg[9]/C}}] -to [get_pins {{sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank1LastWrAddr_reg[0]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank1LastWrAddr_reg[10]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank1LastWrAddr_reg[1]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank1LastWrAddr_reg[2]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank1LastWrAddr_reg[3]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank1LastWrAddr_reg[4]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank1LastWrAddr_reg[5]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank1LastWrAddr_reg[6]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank1LastWrAddr_reg[7]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank1LastWrAddr_reg[8]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpBank1LastWrAddr_reg[9]/D}}] 5.000
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {{sitcp/SiTCP/GMII/GMII_TXBUF/memRdReq_reg[0]/C} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdReq_reg[1]/C}}] -to [get_pins {{sitcp/SiTCP/GMII/GMII_TXBUF/irMemRdReq_reg[0]/D} {sitcp/SiTCP/GMII/GMII_TXBUF/irMemRdReq_reg[1]/D}}] 5.000
set_property src_info {type:XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__0/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__1/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__2/C}] -to [get_pins {sitcp/SiTCP/GMII/GMII_RXCNT/SetPauseTime_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/crcOk_reg/CLR {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[5]/CLR} sitcp/SiTCP/GMII/GMII_RXCNT/ipgOk_reg/CLR {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[3]/CLR} sitcp/SiTCP/GMII/GMII_RXCNT/rcvdMacFlow_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxErr_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxPay_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxPrlTim_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxSfd_reg/CLR}]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__0/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__1/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__2/C}] -to [get_pins {{sitcp/SiTCP/GMII/GMII_TXCNT/ipgCnt_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/ipgCnt_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/ipgCnt_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/ipgCnt_reg[5]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/ipgCnt_reg[6]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/ipgCnt_reg[7]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/ipgCnt_reg[8]/CLR} sitcp/SiTCP/GMII/GMII_TXCNT/ipgOk_reg/CLR {sitcp/SiTCP/GMII/GMII_TXCNT/irMacPauseExe_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/irMacPauseExe_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/irMacPauseExe_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/irMacPauseExe_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/macPauseExe_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/macPauseExe_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/macPauseLd_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/macPauseLd_reg[1]/CLR} sitcp/SiTCP/GMII/GMII_TXCNT/memRe_reg/CLR {sitcp/SiTCP/GMII/GMII_TXCNT/memWa_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/memWa_reg[10]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/memWa_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/memWa_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/memWa_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/memWa_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/memWa_reg[5]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/memWa_reg[6]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/memWa_reg[7]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/memWa_reg[8]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/memWa_reg[9]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[10]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[11]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[12]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[13]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[14]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[15]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[16]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[17]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[18]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[19]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[20]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[21]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[22]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[23]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[5]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[6]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[7]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[8]/CLR} {sitcp/SiTCP/GMII/GMII_TXCNT/pasuseCntr_reg[9]/CLR} sitcp/SiTCP/GMII/GMII_TXCNT/pauseEnb_reg/CLR sitcp/SiTCP/GMII/GMII_TXCNT/pauseExe_reg/CLR sitcp/SiTCP/GMII/GMII_TXCNT/rdOk_reg/CLR sitcp/SiTCP/GMII/GMII_TXCNT/rdReq_reg/CLR}]
set_property src_info {type:XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__0/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__1/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__2/C}] -to [get_pins {{sitcp/SiTCP/GMII/GMII_TXCNT/ipgCnt_reg[1]/PRE} {sitcp/SiTCP/GMII/GMII_TXCNT/ipgCnt_reg[4]/PRE}}]
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__0/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__1/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__2/C}] -to [set _xlnx_shared_i0 [get_pins [list {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[10]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[5]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[6]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[7]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[8]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[9]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0Status_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0Status_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[10]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[5]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[6]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[7]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[8]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[9]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1Status_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1Status_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[10]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[11]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[12]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[13]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[14]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[15]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[16]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[17]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[18]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[19]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[20]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[21]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[22]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[23]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[24]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[25]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[26]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[27]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[28]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[29]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[30]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[31]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[5]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[6]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[7]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[8]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[9]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/irRdAct_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/irRdAct_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[10]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[5]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[6]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[7]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[8]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[9]/CLR} sitcp/SiTCP/GMII/GMII_TXBUF/muxEndTgl_reg/CLR sitcp/SiTCP/GMII/GMII_TXBUF/muxEof_reg/CLR sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsEnb_reg/CLR {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[10]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[5]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[6]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[7]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[8]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[9]/CLR} sitcp/SiTCP/GMII/GMII_TXBUF/phyLinkOk_reg/CLR {sitcp/SiTCP/GMII/GMII_TXBUF/rdAct_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rdAct_reg[1]/CLR} sitcp/SiTCP/GMII/GMII_TXBUF/rdBank_reg/CLR sitcp/SiTCP/GMII/GMII_TXBUF/rdEndDet_reg/CLR {sitcp/SiTCP/GMII/GMII_TXBUF/rshrpMuxTrnsEnd_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rshrpMuxTrnsEnd_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/trnsActDly_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/trnsActDly_reg[1]/CLR} sitcp/SiTCP/GMII/GMII_TXBUF/trnsAct_reg/CLR sitcp/SiTCP/GMII/GMII_TXBUF/wrBank_reg/CLR]]]
set_property src_info {type:XDC file:3 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__0/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__1/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__2/C}] -to [get_pins {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[0]/PRE}]
set_property src_info {type:XDC file:3 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__0/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__1/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__2/C}] -to [get_pins {sitcp/SiTCP/GMII/GMII_RXCNT/SetPauseTime_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/crcOk_reg/CLR {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[5]/CLR} sitcp/SiTCP/GMII/GMII_RXCNT/ipgOk_reg/CLR {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[3]/CLR} sitcp/SiTCP/GMII/GMII_RXCNT/rcvdMacFlow_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxErr_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxPay_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxPrlTim_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxSfd_reg/CLR}]
set_property src_info {type:XDC file:3 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__0/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__1/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__2/C}] -to [get_pins [list sitcp/SiTCP/GMII/GMII_TXBUF/wrBank_reg/CLR {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[10]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[5]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[6]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[7]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[8]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0LastWrAddr_reg[9]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0Status_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0Status_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[10]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[5]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[6]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[7]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[8]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1LastWrAddr_reg[9]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1Status_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1Status_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[10]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[11]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[12]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[13]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[14]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[15]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[16]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[17]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[18]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[19]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[20]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[21]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[22]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[23]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[24]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[25]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[26]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[27]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[28]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[29]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[30]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[31]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[5]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[6]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[7]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[8]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/fcsCal_reg[9]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/irRdAct_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/irRdAct_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[10]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[5]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[6]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[7]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[8]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/memRdAddr_reg[9]/CLR} sitcp/SiTCP/GMII/GMII_TXBUF/muxEndTgl_reg/CLR sitcp/SiTCP/GMII/GMII_TXBUF/muxEof_reg/CLR sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsEnb_reg/CLR {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[10]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[5]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[6]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[7]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[8]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/orLen_reg[9]/CLR} sitcp/SiTCP/GMII/GMII_TXBUF/phyLinkOk_reg/CLR {sitcp/SiTCP/GMII/GMII_TXBUF/rdAct_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rdAct_reg[1]/CLR} sitcp/SiTCP/GMII/GMII_TXBUF/rdBank_reg/CLR sitcp/SiTCP/GMII/GMII_TXBUF/rdEndDet_reg/CLR {sitcp/SiTCP/GMII/GMII_TXBUF/rshrpMuxTrnsEnd_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rshrpMuxTrnsEnd_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/trnsActDly_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/trnsActDly_reg[1]/CLR} sitcp/SiTCP/GMII/GMII_TXBUF/trnsAct_reg/CLR]]
set_property src_info {type:XDC file:3 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__0/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__1/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__2/C}] -to [get_pins {sitcp/SiTCP/GMII/GMII_RXCNT/SetPauseTime_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/crcOk_reg/CLR {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[5]/CLR} sitcp/SiTCP/GMII/GMII_RXCNT/ipgOk_reg/CLR {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[3]/CLR} sitcp/SiTCP/GMII/GMII_RXCNT/rcvdMacFlow_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxErr_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxPay_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxPrlTim_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxSfd_reg/CLR}]
set_property src_info {type:XDC file:3 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__0/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__1/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__2/C}] -to [get_pins {sitcp/SiTCP/GMII/GMII_RXCNT/SetPauseTime_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/crcOk_reg/CLR {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[5]/CLR} sitcp/SiTCP/GMII/GMII_RXCNT/ipgOk_reg/CLR {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[3]/CLR} sitcp/SiTCP/GMII/GMII_RXCNT/rcvdMacFlow_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxErr_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxPay_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxPrlTim_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxSfd_reg/CLR}]
set_property src_info {type:XDC file:3 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__0/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__1/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__2/C}] -to 
set_property src_info {type:XDC file:3 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__0/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__1/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__2/C}] -to [get_pins {sitcp/SiTCP/GMII/GMII_RXCNT/SetPauseTime_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/crcOk_reg/CLR {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[5]/CLR} sitcp/SiTCP/GMII/GMII_RXCNT/ipgOk_reg/CLR {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[3]/CLR} sitcp/SiTCP/GMII/GMII_RXCNT/rcvdMacFlow_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxErr_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxPay_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxPrlTim_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxSfd_reg/CLR}]
set_property src_info {type:XDC file:3 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__0/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__1/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__2/C}] -to [get_pins {sitcp/SiTCP/GMII/GMII_TXBUF/wrBank_reg/CLR sitcp/SiTCP/GMII/GMII_TXBUF/muxEof_reg/CLR sitcp/SiTCP/GMII/GMII_TXBUF/muxEndTgl_reg/CLR {sitcp/SiTCP/GMII/GMII_TXBUF/irRdAct_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rshrpMuxTrnsEnd_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rshrpMuxTrnsEnd_reg[0]/CLR} sitcp/SiTCP/GMII/GMII_TXBUF/rdEndDet_reg/CLR {sitcp/SiTCP/GMII/GMII_TXBUF/bank0Status_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0Status_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rdAct_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rdAct_reg[0]/CLR} sitcp/SiTCP/GMII/GMII_TXBUF/phyLinkOk_reg/CLR {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1Status_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1Status_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/irRdAct_reg[1]/CLR}}]
set_property src_info {type:XDC file:3 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__0/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__1/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__2/C}] -to [get_pins {sitcp/SiTCP/GMII/GMII_RXCNT/SetPauseTime_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/crcOk_reg/CLR {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[5]/CLR} sitcp/SiTCP/GMII/GMII_RXCNT/ipgOk_reg/CLR {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[3]/CLR} sitcp/SiTCP/GMII/GMII_RXCNT/rcvdMacFlow_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxErr_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxPay_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxPrlTim_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxSfd_reg/CLR}]
set_property src_info {type:XDC file:3 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__0/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__1/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__2/C}] -to [get_pins {sitcp/SiTCP/GMII/GMII_TXBUF/wrBank_reg/CLR sitcp/SiTCP/GMII/GMII_TXBUF/muxEof_reg/CLR sitcp/SiTCP/GMII/GMII_TXBUF/muxEndTgl_reg/CLR {sitcp/SiTCP/GMII/GMII_TXBUF/irRdAct_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rshrpMuxTrnsEnd_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rshrpMuxTrnsEnd_reg[0]/CLR} sitcp/SiTCP/GMII/GMII_TXBUF/rdEndDet_reg/CLR {sitcp/SiTCP/GMII/GMII_TXBUF/bank0Status_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0Status_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rdAct_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rdAct_reg[0]/CLR} sitcp/SiTCP/GMII/GMII_TXBUF/phyLinkOk_reg/CLR {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1Status_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1Status_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/irRdAct_reg[1]/CLR}}]
set_property src_info {type:XDC file:3 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__0/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__1/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__2/C}] -to [get_pins {sitcp/SiTCP/GMII/GMII_RXCNT/SetPauseTime_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/crcOk_reg/CLR {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[4]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/ipgCnt_reg[5]/CLR} sitcp/SiTCP/GMII/GMII_RXCNT/ipgOk_reg/CLR {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_RXCNT/muxSel_reg[3]/CLR} sitcp/SiTCP/GMII/GMII_RXCNT/rcvdMacFlow_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxErr_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxPay_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxPrlTim_reg/CLR sitcp/SiTCP/GMII/GMII_RXCNT/rxSfd_reg/CLR}]
set_property src_info {type:XDC file:3 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__0/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__1/C sitcp/SiTCP/SiTCP_INT/SiTCP_RESET_OUT_reg_rep__2/C}] -to [get_pins {sitcp/SiTCP/GMII/GMII_TXBUF/wrBank_reg/CLR sitcp/SiTCP/GMII/GMII_TXBUF/muxEof_reg/CLR sitcp/SiTCP/GMII/GMII_TXBUF/muxEndTgl_reg/CLR {sitcp/SiTCP/GMII/GMII_TXBUF/irRdAct_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rsmpMuxTrnsEnd_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rshrpMuxTrnsEnd_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rshrpMuxTrnsEnd_reg[0]/CLR} sitcp/SiTCP/GMII/GMII_TXBUF/rdEndDet_reg/CLR {sitcp/SiTCP/GMII/GMII_TXBUF/bank0Status_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank0Status_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[2]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rdAct_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/rdAct_reg[0]/CLR} sitcp/SiTCP/GMII/GMII_TXBUF/phyLinkOk_reg/CLR {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[3]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1Status_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/bank1Status_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[1]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/muxFcsSel_reg[0]/CLR} {sitcp/SiTCP/GMII/GMII_TXBUF/irRdAct_reg[1]/CLR}}]
set_property src_info {type:XDC file:3 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */GMII_RXBUF/cmpWrAddr_reg[*]/C}] -to [get_pins -hier -filter {name =~ */GMII_RXBUF/smpWrStatusAddr_reg[*]/D}] 5.000
set_property src_info {type:XDC file:3 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */GMII_TXBUF/orRdAct_reg[*]/C}] -to [get_pins -hier -filter {name =~ */GMII_TXBUF/irRdAct_reg[*]/D}] 5.000
set_property src_info {type:XDC file:3 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */GMII_TXBUF/muxEndTgl_reg/C}] -to [get_pins -hier -filter {name =~ */GMII_TXBUF/rsmpMuxTrnsEnd_reg[0]/D}] 5.000
set_property src_info {type:XDC file:3 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX10Data_reg[*]/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/irMacFlowEnb_reg/D}] 5.000
set_property src_info {type:XDC file:3 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX12Data_reg[*]/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/muxMyMac_reg[*]/D}] 5.000
set_property src_info {type:XDC file:3 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX13Data_reg[*]/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/muxMyMac_reg[*]/D}] 5.000
set_property src_info {type:XDC file:3 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX14Data_reg[*]/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/muxMyMac_reg[*]/D}] 5.000
set_property src_info {type:XDC file:3 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX15Data_reg[*]/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/muxMyMac_reg[*]/D}] 5.000
set_property src_info {type:XDC file:3 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX16Data_reg[*]/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/muxMyMac_reg[*]/D}] 5.000
set_property src_info {type:XDC file:3 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX17Data_reg[*]/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/muxMyMac_reg[*]/D}] 5.000
set_property src_info {type:XDC file:3 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {{sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX18Data_reg[0]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX18Data_reg[1]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX18Data_reg[2]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX18Data_reg[3]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX18Data_reg[4]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX18Data_reg[5]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX18Data_reg[6]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX18Data_reg[7]/C}}] -to [get_pins {{sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[0]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[1]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[2]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[3]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[4]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[5]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[6]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[7]/D}}] 5.000
set_property src_info {type:XDC file:3 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {{sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX19Data_reg[0]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX19Data_reg[1]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX19Data_reg[2]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX19Data_reg[3]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX19Data_reg[4]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX19Data_reg[5]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX19Data_reg[6]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX19Data_reg[7]/C}}] -to [get_pins {{sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[0]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[1]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[2]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[3]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[4]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[5]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[6]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[7]/D}}] 5.000
set_property src_info {type:XDC file:3 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {{sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1AData_reg[0]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1AData_reg[1]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1AData_reg[2]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1AData_reg[3]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1AData_reg[4]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1AData_reg[5]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1AData_reg[6]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1AData_reg[7]/C}}] -to [get_pins {{sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[0]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[1]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[2]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[3]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[4]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[5]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[6]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[7]/D}}] 5.000
set_property src_info {type:XDC file:3 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {{sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1BData_reg[0]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1BData_reg[1]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1BData_reg[2]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1BData_reg[3]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1BData_reg[4]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1BData_reg[5]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1BData_reg[6]/C} {sitcp/SiTCP/SiTCP_INT/SiTCP_INT_REG/regX1BData_reg[7]/C}}] -to [get_pins {{sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[0]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[1]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[2]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[3]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[4]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[5]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[6]/D} {sitcp/SiTCP/GMII/GMII_RXCNT/muxMyIp_reg[7]/D}}] 5.000
set_property src_info {type:XDC file:3 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins -hier -filter {name =~ */SiTCP_INT/SiTCP_RESET_OUT_reg_*/C}] -to [get_pins -hier -filter {name =~ */GMII/GMII_RXCNT/*/CLR}]
set_property src_info {type:XDC file:3 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins -hier -filter {name =~ */SiTCP_INT/SiTCP_RESET_OUT_reg_*/C}] -to [get_pins -hier -filter {name =~ */GMII/GMII_RXCNT/*/PRE}]
set_property src_info {type:XDC file:3 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins -hier -filter {name =~ */SiTCP_INT/SiTCP_RESET_OUT_reg_*/C}] -to [get_pins -hier -filter {name =~ */GMII/GMII_RXBUF/*/CLR}]
set_property src_info {type:XDC file:3 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins -hier -filter {name =~ */SiTCP_INT/SiTCP_RESET_OUT_reg_*/C}] -to [get_pins -hier -filter {name =~ */GMII/GMII_TXBUF/*/CLR}]
